### ISSUE TITLE
Change animation speed

### ISSUE THREAD

**Issue by matt1432** [lucasnlm/antimine-android#465]
I really like this app. However, when I try to go fast the app does not follow along. I have to wait after each animation which can be painful.

I would like the option to disable animations or at least make them quicker, so that I can be as fast as possible.

**Comment by lucasnlm** [comment]
@matt1432 Hi! Thanks for your feedback!
Can you give more details about which animation?
It has almost no animation. So I'm confuse.

**Comment by matt1432** [comment]
I'm talking about the delay after revealing a square, the delay before a square is flagged after pressing a number, etc

**Comment by lucasnlm** [comment]
@matt1432 What device are you using? It shouldn't take any second to review the map. But, if you are using a big map with a slow device, it may take some time to process the map update.

**Comment by sin3point14** [comment]
I have been playing minesweeper for a few years now and am decently fast at it. I think I can relate to what this issues says. 
I think there are 2 problems here:
1. In antimine, when you press a tile, only a border is drawn around the tile, ie it is not processed immediately.

See this:
https://github.com/lucasnlm/antimine-android/assets/43549821/fcb9e455-b8e6-4e33-a879-3b8e75c07390
I held my finger down so antimine didn't register it as a "reveal tile" action, instead just ignored it.

There are some desktop minesweepers that do something like this: https://minesweeper.online/. You can hold your mouse button on a tile and it won't be revealed, but as soon as you lift it will be revealed. I think on desktop this kind of behavior is somewhat acceptable because mouse in general are faster then touch and provide good feedback to your hand and brain. But then there are implementations like https://mzrg.com/js/mine/torus.html which feel a lot better when you want to solve it fast. As soon as a tile is revealed a fast minesweeper player is already planning their next moves even though their touch/mouse action may still not be complete.

2. There is something weird happening between my finger lifting and the tile being revealed

realtime:
https://github.com/lucasnlm/antimine-android/assets/43549821/d6919bc6-034a-44d2-b8d3-912dd07af930
I have slowed this down by 0.125x:
https://github.com/lucasnlm/antimine-android/assets/43549821/7d8e713f-6202-4e88-8f1f-713e09143c2f
The white circle denotes my touch action, and in real time it feels to me that it takes some amount of time for the tiles to be revealed. However In this slowed down video it doesn't! I think the culprit is the rounded box that appears on the box I pressed and fades out slowly. "Slowly" here is relative: It takes considerable amount of time to vanish compared to the time interval of my find lifting and the tiles being revealed. To my brain it feels like as long as there are changes happening in the board UI, the tiles are still being revealed. It is an illusion, but it works well in slowing my actions .

This feel jarring because the reveal timing doesn't match my pressing or lifting of finger from the screen and really breaks my rhythm



I think the solution would be to just process the "tile reveal" or "tap on number" as soon as the user's finger lands on the screen and move the gray box entirely or as soon as the times are revealed.
Or if that doesn't sound like good UX for the general audience, maybe an option can be added which "disables animation", though then there are 2 types of animation I talk about here, but that matter is just technicalities ¯\\\_(ツ)_/¯.


If I find some time, I'll try to create a PoC where I remove these 2 things.

**Comment by Clozent** [comment]
@lucasnlm I think he meant the fact that after pressing a tile (including numbers), the action doesn't happen immediately, having a "tap" animation before tiles are revealed / flagged.

The problem is that the tap animation plays _after_ a tap, when it should play _during_ a tap.

Tiles should be revealed immediately after raising the finger (unless the player has slid their finger past the tile, indicating that they did not mean to tap it), and any animation that plays after the player has done so should not obscure the tile.

**Comment by sin3point14** [comment]
Just to confirm, did you run 17.7.0? I was looking at the changelog just to see what fixed the bug, but couldn't spot anything 🤔
