### ISSUE TITLE
Speed up time between hitting a mine and showing the popup to start a new game

### ISSUE THREAD

**Issue by vertigo220** [lucasnlm/antimine-android#495]
**Is your feature request related to a problem? Please describe.**
It takes a second or two after losing for it to pop up and say you lost and allow starting a new game. This should be instant. Especially when first starting and randomly tapping to try and open up some areas, generally you will have to restart multiple times in quick succession, and this delay is annoying.

**Describe the solution you'd like**
Eliminate the delay so as soon as a mine is hit the pop-up shows.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lucasnlm** [comment]
It has a delay to allow the user to see the error before show the dialog. If I show the dialog immediately, a new user may not understand what happened.

> Especially when first starting and randomly tapping to try and open up some areas,
I think that is not a good motivation to remove the delay. Ideally, there's no need to randomly tapping because the levels are tested as soon you open the first area. So, all levels should be resolved without random actions.

So, I think the cost to remove the delay is bigger than keep it.
Alternatively, there's already an option on Settings ("show windows" or something) that don't show these dialogs when you win or lost a game. Maybe disable that option is what you need?
Can you check, please?

**Comment by vertigo220** [comment]
The problem with that is the delay is nowhere near long enough to be able to see and fully comprehend what was done wrong, yet it's long enough to be frustrating. Almost every time I lose, despite the delay, I have to select continue if I want to see what I did wrong (leading to #498), so all the delay does is get in the way if I want to just quickly restart and make it take longer to be able to select continue to be able to analyze things.

That said, the option you mentioned does eliminate the delay issue. The only problem with that is having to reach way up to the top of the screen to hit the restart button instead of having an option within easier reach as with the popup, but that's minor, so I'll close this.
