### ISSUE TITLE
Improvements / Feature requests

### ISSUE THREAD

**Issue by girst** [lucasnlm/antimine-android#57]
Hi, I just stumbled upon this app in fdroid's RFP tracker. If you don't mind, I would like to suggest some improvements/feature requests:

- chording when single-tapping open square:
  in many implementations, clicking on a opened square that has the exact amount of neighbours flagged, opens all non-flagged neighbouring cells. if the wrong amount of mines are flagged, the current behaviour could still be used.
- fast-flag mode
  a button that toggles whether clicking on cells opens them, or flags them.
- zoom out
  sometimes I would like to get a better overview of things

I don't know anything about android programming, so I can't send PRs, but I'll gladly chip in with some beer money in return ;)

**edit**: oh, and a bug report: when dragging the playfield around, the screen stutters / drops frames (on my nexus 5 w/ lineageos 14.1 / android 7.1)

**Comment by lucasnlm** [comment]
Thanks for your feedback!

About your points:
- Currently If you long press an opened square it will open all neighbors squares, except if flagged. Is this the same behavior?
- About fast-flag: I agree. It should have that option. I will open an issue exclusively to it.
- About zoom out. I would be really cool. Currently you can share an image of the whole minefield and zoom in / out. However it's not possible to do it in game. I will open an issue to that feature too.
- And that drops frame I'm investigating. It happens due to issue with RecyclerView and horizontal scrolling. It usually happens on large minefields, but it's bad. :(

Thank you again for the feedback! 😄

**Comment by girst** [comment]
On Wed, Apr 22, 2020 at 01:11:00PM -0700, Lucas Nunes wrote:
>- Currently If you long press an opened square it will open all 
>neighbors squares, except if flagged. Is this the same behavior?

oh, i didn't think about long-clicking! yes, that's more or less the 
described behaviour, except that it also chords when the wrong number of 
adjacent mines are flagged. if it only triggers when exactly the right 
amount of mines are flagged, you can use it instead of counting the 
adjacent flags. also, subjectively, long-clicking breaks my flow quite a 
bit, hence my request for it to happen on normal click.

**Comment by lucasnlm** [comment]
Hi, @girst!
Fast flag is available on `7.2.0`.

**Comment by girst** [comment]
On Mon, Jun 29, 2020 at 09:30:31AM -0700, Lucas Nunes wrote:
>Fast flag is available on `7.2.0`.

great! looking forward to trying it out once it hits fdroid. :)
