### ISSUE TITLE
Zoom out

### ISSUE THREAD

**Issue by lucasnlm** [lucasnlm/antimine-android#59]
Zoom out
sometimes I would like to get a better overview of things
from #57 by @girst

**Comment by lucasnlm** [comment]
@BloodRaven0 Thanks for report!

I'm working on a new presentation layer to replace completely using OpenGL instead of RecyclerView.
By doind this I hope to fix that issue and bring zoom out to the game.

**Comment by lucasnlm** [comment]
Almost there. Any feedback about it?

<img src="https://user-images.githubusercontent.com/1326126/112699567-e388c100-8e6a-11eb-99eb-4d0f2a6154d5.png" width="250px" /> <img src="https://user-images.githubusercontent.com/1326126/112699599-f4d1cd80-8e6a-11eb-91b3-dfcc00140c7c.png" width="250px" />

**Comment by girst** [comment]
On Fri, Mar 26, 2021 at 03:40:40PM -0700, Lucas Nunes wrote:
>Almost there. Any feedback about it?

without the numbers, i think a lot of context is going away as well.  
the numbers tell you where a move can be done.

apologies for the "why not just" question, but i'd be interested in what 
the challenges are for the following: with the coming opengl based 
rendering, shouldn't it be possible to implement pinch-to-zoom? as far 
as i remember, zooming was hard to implement, because scaling the 
built-in widgets was problematic?

**Comment by lucasnlm** [comment]
Yes! I did a pinch-to-zoom. So the numbers are not visible only when they get too small.
So, it's not a two states mode (normal and zoom out). You can pinch-to-zoom and adjust whatever zoom level you want.

**Comment by girst** [comment]
On Sat, Mar 27, 2021 at 07:37:51AM -0700, Lucas Nunes wrote:
>Yes! I did a pinch-to-zoom. So the numbers are not visible only when they get too small.

That's actually sensible. maybe once they are too small, maybe put a 
correctly-colored dot in the cell?

>So, it's not a two states mode (normal and zoom out). You can pinch-to-zoom and adjust whatever zoom level you want.

Sounds great! Can't wait! :D

**Comment by lucasnlm** [comment]
Zoom out it's available on `10.0.0`.
It currently it not available on F-droid due to a build issue (I'll check it later).
