### ISSUE TITLE
Implement game generator without guessing

### ISSUE THREAD

**Issue by lucasnlm** [lucasnlm/antimine-android#64]
Currently the generated games may have guessing situations. The game generator should be updated to avoid  guessing situations.

**Comment by lucasnlm** [comment]
This feature is now available on `7.3.0` release.

I've implemented a brute force algorithm and a interface to easily add new implementations.
They are both [here](https://github.com/lucasnlm/antimine-android/tree/master/common/src/main/java/dev/lucasnlm/antimine/common/level/solver).

**Comment by luke-clifton** [comment]
I have 8.3.0 and the game generated this which required guessing.

Note this is at the edge of the board.

![Screenshot_20201020-142915_1](https://user-images.githubusercontent.com/6327304/96567143-0aa9f800-12f9-11eb-9909-dc9839229fd0.png)

**Comment by lucasnlm** [comment]
@luke-clifton The current implementation was changed to try find games without guessing. If it takes too long to find a 100% no-guess game it will stop searching. I did it to have a better UX (it usually happens when a game has too many mines).

**Comment by petersohn** [comment]
What's the maximum expected mine density that's safe? Here is a screenshot of a guessing scenario on a 30 mine standard field.

![2020-11-08 21 27 51](https://user-images.githubusercontent.com/2822847/98484435-af8c6680-220f-11eb-94d9-24e58b642e73.jpg)

**Comment by lucasnlm** [comment]
@petersohn Depending on how my mines it must place and the area available it's impossible (or it take too much time) to find a 100% solvable level. So it fails in some cases. I think that is what happened to you. 😞

**Comment by petersohn** [comment]
I looked at the code, and the current no-guessing algorithm is actually not what I want. It only accepts a map if it can be solved by brute-force, i.e. by long-clicking on the numbers. This will get boring pretty fast. I like maps where I have to make some more advanced deductions, but I don't have to guess randomly. This is actually pretty rare.

So I threw together a more sophisticated algorithm. I'm not fluent in either Kotlin or Android development, so instead of creating a PR, I made a simple Python emulator / implementation, here: https://github.com/petersohn/mine-solver . Using this or something similar for the no-guessing algorithm would result in a higher chance of accepting a map, and also in possibly more challenging, but still solvable, maps.

Note that I threw this together in one afternoon, so there might be errors. They work fine for some tests that I tried it on. There are also possibilities for performance improvements, which might be important when running it multiple times in a row on an Android.

**Comment by BloodRaven0** [comment]
Another far simpler solution would be to just allow players to win if all mines are marked correctly, but not all squares are revealed.
Since it could be seen as cheating (but it would require far more time to solve this way then the normal way, hence not being a time-competetive method), it could be a toggle-able option in the settings.

**Comment by lucasnlm** [comment]
@petersohn Sorry for take so much time to implement your suggestion. 😓 
I got your code, but I'm still working on fix some render issues and adding support to opengl.

I hope to improve the generator soon.

**Comment by lucasnlm** [comment]
@BloodRaven0 It's valid as a toggle-able option. As default It may confuse some users that aren't used to this.

**Comment by BloodRaven0** [comment]
@lucasnlm Yeah, I wouldn't have it as the default option either, even though I've seen some minesweeper apps leave it on as the default, and even have no option to turn it off. Still, it's not a perfect solution, because sometimes you might have a guessing scenario which is preventing you from revealing a larger part of the field, and this method can't help you with that.

**Comment by yw662** [comment]
I just experienced an end game guessing condition with guess free on.
Though I don't know how to put some details here.

**Comment by Ledarium** [comment]
![Screenshot_20210708-005147](https://user-images.githubusercontent.com/10389237/124833567-e87f0580-df6d-11eb-960f-2b533e903a08.png)
Still have guessing situation even though 'No guessing' mode is on. Thanks for the awesome game version overall!

**Comment by lucasnlm** [comment]
@Ledarium Have you check the current version? It uses a new algorithm.
